In [1]:
import torch

import torch.nn as nn

In [ ]:
class Model(nn.Module):


    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):

        out = self.linear(features)
        out = self.sigmoid(out)

        return out
    
    

In [3]:
# create dataset

features = torch.rand(10,5)

In [6]:
model = Model(features.shape[1])

In [7]:
model.forward(features)

tensor([[0.5639],
        [0.5672],
        [0.6199],
        [0.5600],
        [0.6403],
        [0.5361],
        [0.5490],
        [0.6677],
        [0.6480],
        [0.5878]], grad_fn=<SigmoidBackward0>)

In [8]:
model.linear.weight

Parameter containing:
tensor([[-0.1991,  0.0991,  0.3722,  0.1108,  0.4284]], requires_grad=True)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

[2] Second Neuron

In [ ]:
class Model(nn.Module):


    def __init__(self, num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2= nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features): # we are doing this step by step which is very cumbersome and we can simplify it using sequentical
        out = self.linear1(features)
        out=self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [ ]:
features = torch.rand(10,5)

model = Model(features.shape[1])

In [4]:
model.forward(features)

tensor([[0.6165],
        [0.6325],
        [0.6154],
        [0.6345],
        [0.6297],
        [0.6250],
        [0.6251],
        [0.6110],
        [0.6254],
        [0.6158]], grad_fn=<SigmoidBackward0>)

In [5]:
model(features)

tensor([[0.6165],
        [0.6325],
        [0.6154],
        [0.6345],
        [0.6297],
        [0.6250],
        [0.6251],
        [0.6110],
        [0.6254],
        [0.6158]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear1.weight

Parameter containing:
tensor([[-0.3841,  0.2557, -0.3469, -0.4040,  0.1429],
        [ 0.2199,  0.1916,  0.2807, -0.1158,  0.1612],
        [ 0.1369,  0.3705, -0.3708, -0.0006,  0.0046]], requires_grad=True)

In [9]:
model.linear2.weight

Parameter containing:
tensor([[-0.2686,  0.1039, -0.0903]], requires_grad=True)

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Using Sequential

In [12]:
class Model(nn.Module):


    def __init__(self, num_features):

        super().__init__()
        self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())



    def forward(self,features): # we are doing this step by step which is very cumbersome and we can simplify it using sequentical
        out = self.network(features)

        return out

In [13]:
features = torch.rand(10,5)

model = Model(features.shape[1])

In [14]:
model.forward(features)

tensor([[0.5377],
        [0.5304],
        [0.5364],
        [0.5449],
        [0.5257],
        [0.5441],
        [0.5733],
        [0.5195],
        [0.5363],
        [0.5374]], grad_fn=<SigmoidBackward0>)