YT : https://www.youtube.com/watch?v=MKxEbbKpL5Q

In [2]:
!pip install pandas scikit-learn

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ------------- -------------------------- 3.9/11.3 MB 19.6 MB/s eta 0:00:01
   -------------------------- ------------- 7.6/11.3 MB 18.8 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 18.2 MB/s  0:00:00
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   --------------- ------------------------ 3.4/8.9 MB 22.3 MB/s eta 0:00:01
   ----------------------------------- ---- 7.9/8.9 MB 19.4 MB/s eta 0:00:01
   ---------------------------------------- 8.9/8.9 MB 18.4 MB/s  0:00:00
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   --- ------------------------------------ 3.9/41.3 MB 19.5 MB/s eta 0:00:02
   ------- -------------------------------- 7.6/41.3 MB 18.8 MB/s eta 0:00:02
   ---------- ----------------------------- 11.3/41.3 MB 18.0 MB/s eta 0:00:02
   -------------- ------------------------- 14.9/41.3 MB 18.4 MB/s eta 0:00:02
   --------------

In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [9]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[-0.60107448, -1.01785409, -0.59144536, ..., -1.01933729,
         0.34322698, -0.46791701],
       [ 1.03542061,  0.32300681,  1.07451042, ...,  0.56290508,
        -0.73816201, -0.38805344],
       [-0.22122483,  0.2162947 , -0.17298646, ...,  0.52785926,
         1.34936046,  0.97826109],
       ...,
       [-0.74958712, -0.47269438, -0.73950267, ..., -0.77005488,
        -0.54020729, -0.19486995],
       [-0.0984163 , -0.15487787, -0.11451005, ...,  0.2109232 ,
        -0.1066701 ,  0.30967353],
       [-0.33546533, -0.26158998, -0.29201293, ..., -0.07553825,
        -0.54347927,  0.23520615]], shape=(455, 30))

In [13]:
y_train

349    B
156    M
43     M
134    M
372    M
      ..
385    M
438    B
142    B
523    B
518    B
Name: diagnosis, Length: 455, dtype: object

In [14]:
encoder = LabelEncoder()

In [15]:
y_train= encoder.fit_transform(y_train)

y_test = encoder.transform(y_test)

In [16]:
y_train

array([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,

In [17]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0])

In [18]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [21]:
X_test_tensor.shape

torch.Size([114, 30])

In [20]:
y_train_tensor

tensor([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,

# Defining Neural Network

In [39]:
class MySimpleNN():

    def __init__(self,X):

        self.weights = torch.rand(X.shape[1],1,dtype = torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
    
    def forward(self,X):

        z = torch.matmul(X,self.weights) + self.bias # wTx+b

        y_pred = torch.sigmoid(z)

        return y_pred
        
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        


        
        

In [25]:
learning_rate =0.1

epochs = 25

In [ ]:
torch.rand(X_train.shape[1],1,)

tensor([[0.6898],
        [0.7703],
        [0.8524],
        [0.3776],
        [0.7076],
        [0.6708],
        [0.5776],
        [0.8135],
        [0.1720],
        [0.7749],
        [0.4146],
        [0.3933],
        [0.7956],
        [0.3998],
        [0.8155],
        [0.4616],
        [0.2208],
        [0.6596],
        [0.9619],
        [0.3098],
        [0.6872],
        [0.5279],
        [0.6785],
        [0.8314],
        [0.2749],
        [0.5775],
        [0.7531],
        [0.3124],
        [0.7794],
        [0.3805]])

In [43]:
learning_rate =0.125

epochs = 250

In [27]:
model = MySimpleNN(X_train_tensor)

In [29]:
model.weights,model.bias

(tensor([[0.3269],
         [0.6271],
         [0.4850],
         [0.2025],
         [0.5025],
         [0.2837],
         [0.2860],
         [0.7533],
         [0.5859],
         [0.3032],
         [0.7474],
         [0.0019],
         [0.6155],
         [0.4673],
         [0.1768],
         [0.3494],
         [0.5983],
         [0.3840],
         [0.4991],
         [0.0191],
         [0.5695],
         [0.6038],
         [0.5695],
         [0.0030],
         [0.1160],
         [0.3097],
         [0.9567],
         [0.3863],
         [0.8194],
         [0.3504]], dtype=torch.float64, requires_grad=True),
 tensor([0.], dtype=torch.float64, requires_grad=True))

In [44]:
model = MySimpleNN(X_train_tensor)

# define loop

for epoch in range(epochs):
    # forward paas

    y_pred = model.forward(X_train_tensor)
   

    # loss calculate
    loss = model.loss_function(y_pred,y_test_tensor)
    print(f'Epoch:{epoch+1},Loss : {loss.item()}')


    # backward pass

    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights-= learning_rate * model.weights.grad

        model.bias -=learning_rate * model.bias.grad

    # zero gradients

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    

Epoch:1,Loss : 3.9776027270809093
Epoch:2,Loss : 3.834475348839349
Epoch:3,Loss : 3.6767136004390397
Epoch:4,Loss : 3.5078453498798594
Epoch:5,Loss : 3.335071921417582
Epoch:6,Loss : 3.1610868779052423
Epoch:7,Loss : 2.982871194485778
Epoch:8,Loss : 2.803597117060661
Epoch:9,Loss : 2.6136705769963133
Epoch:10,Loss : 2.416422579054897
Epoch:11,Loss : 2.2197481809634385
Epoch:12,Loss : 2.0198777618039405
Epoch:13,Loss : 1.8157967750846984
Epoch:14,Loss : 1.6256220715813134
Epoch:15,Loss : 1.4508182845004158
Epoch:16,Loss : 1.2925548112455743
Epoch:17,Loss : 1.1583409780920693
Epoch:18,Loss : 1.0503837742129667
Epoch:19,Loss : 0.9685029731932822
Epoch:20,Loss : 0.9095578164319562
Epoch:21,Loss : 0.8683703388105112
Epoch:22,Loss : 0.8393963374645235
Epoch:23,Loss : 0.8181713023954538
Epoch:24,Loss : 0.8017671102137286
Epoch:25,Loss : 0.7884555092089539
Epoch:26,Loss : 0.7772468335480623
Epoch:27,Loss : 0.7675653356663902
Epoch:28,Loss : 0.7590605403776709
Epoch:29,Loss : 0.7515053055331962

In [51]:
with torch.no_grad():

    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.5).float()

    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6354262828826904


In [48]:
y_pred

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      