In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import sklearn

In [24]:
df = pd.read_csv(r"D:\LEARNING\PYTORCH\DATASET\Boston.csv")

In [25]:
df

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0             1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1             2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2             3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3             4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4             5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...   
501         502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1   
502         503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1   
503         504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1   
504         505  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1   
505         506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1   

     tax  ptratio   black  lstat  medv  
0    296     15.3  396.90   4.98  24.0  
1    242     17.8  396.90   9.14  21.6  
2    242     17.8  392.83   4.03  34.7  
3    222     18.7  394.63   2.94  33.4  
4    222     18.7  396.90   5.33  36.2  
..   ...      ...     ...    ...   ...  
501  273     21.0  391.99   9.67  22.4  
502  273     21.0  396.90   9.08  20.6  
503  273     21.0  396.90   5.64  23.9  
504  273     21.0  393.45   6.48  22.0  
505  273     21.0  396.90   7.88  11.9  

[506 rows x 15 columns]

In [26]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [27]:
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [29]:
X=df.iloc[:,:-1]

In [31]:
X

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [32]:
y = df["medv"]

In [33]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [39]:
y_test

173    23.6
274    32.4
491    13.6
72     22.8
452    16.1
       ... 
418     8.8
117    19.2
42     25.3
322    20.4
347    23.1
Name: medv, Length: 127, dtype: float64

In [40]:
X_train_tensor= torch.tensor(X_train.to_numpy(),dtype=torch.float32)
X_test_tensor= torch.tensor(X_test.to_numpy(),dtype=torch.float32)

In [41]:
X_train_tensor

tensor([[9.1030e-02, 0.0000e+00, 2.4600e+00,  ..., 1.7800e+01, 3.9412e+02,
         4.8200e+00],
        [3.5350e+00, 0.0000e+00, 1.9580e+01,  ..., 1.4700e+01, 8.8010e+01,
         1.5020e+01],
        [3.5780e-02, 2.0000e+01, 3.3300e+00,  ..., 1.4900e+01, 3.8731e+02,
         3.7600e+00],
        ...,
        [1.5010e-02, 8.0000e+01, 2.0100e+00,  ..., 1.7000e+01, 3.9094e+02,
         5.9900e+00],
        [1.1160e+01, 0.0000e+00, 1.8100e+01,  ..., 2.0200e+01, 1.0985e+02,
         2.3270e+01],
        [2.2876e-01, 0.0000e+00, 8.5600e+00,  ..., 2.0900e+01, 7.0800e+01,
         1.0630e+01]])

In [47]:
X_test_tensor.shape

torch.Size([127, 13])

In [45]:
y_train_tensor= torch.tensor(y_train.to_numpy(),dtype=torch.float32)
y_test_tensor= torch.tensor(y_test.to_numpy(),dtype=torch.float32)

In [46]:
y_train_tensor

tensor([37.9000, 15.6000, 45.4000, 15.7000, 22.6000, 14.5000, 18.7000, 17.8000,
        16.1000, 20.6000, 31.6000, 29.1000, 15.6000, 17.5000, 22.5000, 19.4000,
        19.3000,  8.5000, 20.6000, 17.0000, 17.1000, 14.5000, 50.0000, 14.3000,
        12.6000, 28.7000, 21.2000, 19.3000, 23.1000, 19.1000, 25.0000, 33.4000,
         5.0000, 29.6000, 18.7000, 21.7000, 23.1000, 22.8000, 21.0000, 48.8000,
        14.6000, 16.6000, 27.1000, 20.1000, 19.8000, 21.0000, 41.3000, 23.2000,
        20.4000, 18.5000, 29.4000, 36.4000, 24.4000, 11.8000, 13.8000, 12.3000,
        17.8000, 33.1000, 26.7000, 13.4000, 14.4000, 50.0000, 22.0000, 19.9000,
        23.8000, 17.5000, 12.7000,  5.6000, 31.1000, 26.2000, 19.4000, 16.7000,
        13.8000, 22.9000, 15.3000, 27.5000, 36.1000, 22.9000, 24.5000, 25.0000,
        50.0000, 34.9000, 31.7000, 24.1000, 22.1000, 14.1000, 42.8000, 19.3000,
        32.2000, 26.4000, 21.8000, 21.7000,  8.3000, 46.7000, 43.1000, 31.5000,
        10.5000, 16.7000, 20.0000, 33.30

In [59]:
class LinearRegression(nn.Module):

    def __init__(self,num_features):
        super().__init__()

        self.linear = nn.Linear(num_features,1)

    def forward(self,x):
        return self.linear(x)
    

In [50]:
model =LinearRegression(X_train_tensor.shape[1])

In [68]:
model.forward(X_train_tensor)

tensor([[nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [n

In [53]:
loss_f = nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(),lr = 0.01)

### Training Loop

In [67]:
epochs = 1

for epoch in range(epochs):

    y_pred = model(X_train_tensor)

    loss = loss_f(y_pred.view(-1,1),y_train_tensor.view(-1,1))
    print(loss)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    print(f'Epoch {epoch+1},Loss:{loss.item()}')
    

tensor(nan, grad_fn=<MseLossBackward0>)
Epoch 1,Loss:nan


In [58]:
y_pred

tensor([[nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [n